info:
  name: Provider Onboarding

server:
  port: ${PORT:8080}
logging:
  level:
    com.stewartandrews: trace
spring:
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ssZ
    serialization:
      write-dates-as-timestamps: false
  profiles:
    active: dpalocal